### ISSUE TITLE
Configure Display

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/AyushmanBhavaGUI#2]
5" Display needs to be configured!

**Comment by virendrasuryavanshi** [comment]
Configured the Display and Tested it's working but not sure about the Touch Screen as it didn't work when I tried it.

![31472685_1034062466759761_5692808352883539968_n](https://user-images.githubusercontent.com/24255721/39405077-d6eb6c3a-4bbb-11e8-9197-1a3ae8a8c3ac.jpg)

**Comment by virendrasuryavanshi** [comment]
Touchscreen also Configured. Now we need a stylus to use Touchscreen as it's not much precise so it can't easily detect our touch.

**Comment by shreyasbapat** [comment]
Stylus is an issue! Let's keep this open untill we figure out something. Is this a Capacitive touch or resistive?

**Comment by virendrasuryavanshi** [comment]
Resistive Touch, that's why it's not able to detect our Finger properly.

**Comment by shreyasbapat** [comment]
Okay! 😅

**Comment by prabhakarpd7284** [comment]
We can attach a mouse to the rpi and put it outside the machine to use it as an alternative to the touch.

**Comment by shreyasbapat** [comment]
Configured
