### ISSUE TITLE
Flash Ubuntu MATE 18.04 (If available) In RPi

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/AyushmanBhavaGUI#3]
Currently 16.04.2 is available (as per my knowledge)

**Comment by shreyasbapat** [comment]
Tried Flashing! :disappointed:  Assigned to Suryavanshi

**Comment by virendrasuryavanshi** [comment]
Flashed it and checked it with Pi, it's working :)
Close the Issue. @shreyasbapat

**Comment by shreyasbapat** [comment]
Probably issue in depacka ging
