### ISSUE TITLE
Make a 5" screen deployable Front-End for web-app

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/AyushmanBhavaGUI#4]
Navneet and Suryavanshi are assigned for this!

**Comment by shreyasbapat** [comment]
Front end bro. Video streaming can be handled by Prabhakar only

**Comment by virendrasuryavanshi** [comment]
Sorry, bro, I don't do Front-end, tell anything else with the backend I will do it.

**Comment by shreyasbapat** [comment]
Did this! Closing
